title: Faruk.love
email: hello@faruk.love
description: >- # this means to ignore newlines until "baseurl:"
  This site is a personal page and link forwarding domain.
  Link forwards may become obsolete, but never die.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://faruk.love" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kurafire
github_username:  kurafire

# Build settings
theme: jekyll-theme-time-machine

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalinks
permalink: /:categories/:title
